### ISSUE TITLE
Error only in production

### ISSUE THREAD

**Issue by satyamdorville** [A-Tokyo/react-native-stripe-checkout-webview#63] opened 2021-05-21 18:50 UTC
Sorry for lack of info on issue 62
In fact i have this error on screenshot only when passing on production
All my keys are corrects....
So i was wondering if its because the checkout is on a connected account of my main account (Connect feature in Stripe)
Have you got tips on that error please ?
Thanks
![IMG_5507](https://user-images.githubusercontent.com/8899089/119184768-cd9b1500-ba43-11eb-827b-e0a7ea4c0ba8.PNG)

**Comment by A-Tokyo** [comment] 2021-05-21 18:56
Duplicate of https://github.com/A-Tokyo/react-native-stripe-checkout-webview/issues/62#issuecomment-846171551.

**Closed by A-Tokyo** 2021-05-21 18:56 UTC
